spring.datasource.url=jdbc:postgresql://dpg-d69pdep5pdvs738mf0og-a.ohio-postgres.render.com/orcamento_db_61m2?sslmode=require
spring.datasource.username=orcamento_db_61m2_user
spring.datasource.password=A0AKkgCPvy4FZi66p2XyH032iaUn2l2d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082