server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
api.security.token.secret=9839be35e537b9d52f59847cbe2c8bc2137c0b278eda29138bf67e53601a0999